### ISSUE TITLE
when is the release?

### ISSUE THREAD

**Issue by TheHolyTachanka** [PKD667/Soviet#1]
i need it

**Comment by TheHolyTachanka** [comment]
k good luck with code im gonna switch to this ngl

**Comment by PKD667** [comment]
Ok so I will release the very beta version tomorrow ( without gui , and manual kernel config and grub installation)

**Comment by PKD667** [comment]
I think that I could make a gui version with an installer fort the 12-15 march

**Comment by TheHolyTachanka** [comment]
its april

**Comment by PKD667** [comment]
You're right it's April (I need to touch grass)

**Comment by TheHolyTachanka** [comment]
i would help but im scared of c so good luck

**Comment by PKD667** [comment]
I understand thank for the readmes
